<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */

// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';

    $title = $block->getTitle();
    $items = $block->getProductCollection()->getItems();
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $getAddToCartUrl = fn($product) => $block->escapeUrl($block->getAddToCartUrl($product));
    $jsId = $block->getJsId();
    $labelOnsale = __('Ends In');
    $labelsaleStart = __('Starts In');

}
?>

<?php if ($exist): ?>
    <div class="block widget block-new-products <?= /* @noEscape */ $mode ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?= $block->escapeHtml($title) ?></strong>
            <div class="count-down-event" data-bind="scope: 'count-down-<?= /* @noEscape */ $jsId ?>'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                <?php foreach ($items as $_item): ?>
                <li class="product-item">
                    <div class="product-item-info">
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                            class="product-item-photo">
                            <?php if ($percent = $block->getDiscountPercentage($_item)): ?>
                                <div class="discount-percent-wrap" >
                                    <span class="discount-percent">
                                        <?= /* @noEscape */ $percent .'%' ?>
                                    </span>
                                </div>
                            <?php endif; ?>
                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </a>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                    href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                    class="product-item-link">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>
                            <?= $block->getProductPriceHtml($_item, $type); ?>

                        <?php if ($templateType): ?>
                            <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                        <?php endif; ?>

                        <?php if ($showCart): ?>
                            <div class="product-item-actions">
                            <?php if ($showCart): ?>
                                <div class="actions-primary">
                                <?php if ($_item->isSaleable()): ?>
                                    <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                        <button class="action tocart primary"
                                                data-mage-init='{
                                                    "redirectUrl":{
                                                        "url":"<?= /* @noEscape */ $getAddToCartUrl($_item) ?>"
                                                    }
                                                }'
                                                type="button"
                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                        </button>
                                    <?php else: ?>
                                        <?php
                                            $postData = $block->getPostData(
                                                $getAddToCartUrl($_item),
                                                ['product' => (int) $_item->getEntityId()]
                                            )
                                        ?>
                                        <button class="action tocart primary"
                                                data-post='<?= /* @noEscape */ $postData ?>'
                                                type="button"
                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                        </button>
                                    <?php endif; ?>
                                <?php else: ?>
                                        <?php if ($_item->isAvailable()): ?>
                                            <div class="stock available">
                                                <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                            </div>
                                        <?php else: ?>
                                            <div class="stock unavailable">
                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                            </div>
                        <?php endif; ?>
                        </div>
                    </div>
                    </li>
                <?php endforeach ?>
                </ol>
            </div>
            <?php if ($block->getUrlShowMore()): ?>
                <div class="btn-show-more-wrap">
                    <a href="<?= $block->escapeUrl($block->getUrlShowMore()); ?>">
                        <?= $block->escapeHtml(__('See More Offers')) ?>
                    </a>
                </div>
            <?php endif;?>

        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "count-down-<?= /* @noEscape */ $jsId ?>": {
                            "component": "Ecommage_HotDealWidget/js/count-down",
                            "dateFrom": "<?= /* @noEscape */ $block->getDateFrom() ?>",
                            "dateTo": "<?= /* @noEscape */ $block->getDateTo() ?>",
                            "labelOnsale": "<?= $block->escapeHtml($labelOnsale) ?>",
                            "labelsaleStart": "<?= $block->escapeHtml($labelsaleStart) ?>"
                        }
                    }
                }
            }
        }
    </script>
<?php endif;?>

