<?php
echo $block->sayHello();
?>

<table>
  <tr>
    <th class="post-id">Id</th>
    <th class="post-name">Name</th>
    <th>Content</th>
  </tr>

<?php foreach($block->getPostCollection() as $key=>$post): ?>
        <tr>
           <td><?= $post->getPostId() ?></td>
           <td><?= $post->getName() ?></td>
           <td><?= $post->getPostContent() ?></td>
        </tr>
<?php endforeach; ?>
</table> 
<?php
  // dd($block->getCustomerByEmail('tmail2@gmail.com'));
?>
<h2>get customer collection</h2>
<table>
  <?php foreach($block->getFilteredCustomerCollection() as $key=>$customer): ?>
          <tr>
            <td><?= $customer->getEmail() ?></td>
            <td><?= $customer->getName() ?></td>
          </tr>
  <?php endforeach; ?>
</table>
