<?php
    $products = $block->getSliderData();
    $helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<div class="carousel-wrap">
    <div class="product-slider owl-carousel owl-theme">
        <?php foreach ($products as $product): ?>
            <?php //dd($product->getData()) ?>
            <div class="product-item">
                <a class="product-image-container" href="<?= $product->getProductUrl(); ?>">
                    <img src="<?= $block->getMainImageUrl($product); ?>" />
                </a>
                <h3 class="product-name">
                    <a href="<?= $product->getProductUrl(); ?>">
                        <?= __($product->getName()); ?>
                    </a>
                </h3>
                <div class="product-desc">
                    <?= $helper->productAttribute($product, $product->getData('short_description'), 'short_description'); ?>
                </div>
                <strong class="product-ecommage text-left">
                    <?= __('Ecommage: '.$product->getEcommage()); ?>
                </strong>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".owl-carousel": {
            "Ecommage_Attributes/js/scripts-slider": {}
        }
    }
</script>